// Copyright 2015-2022 Manus

#pragma once

// Set up a Doxygen group.
/** @addtogroup FManusLiveLinkUser
 *  @{
 */

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Roles/LiveLinkAnimationTypes.h"
#include "ManusReplicator.generated.h"

//-----------------------------------------------------------------------------
//
USTRUCT()
struct FManusReplicatedFrameData
{
	GENERATED_BODY()

	UPROPERTY()
	int ManusDashboardUserIndex = 0;
	
	UPROPERTY()
	class UManusSkeleton* ManusSkeleton = NULL;

	UPROPERTY()
	TArray<FTransform> MayoTransforms;
};

//-----------------------------------------------------------------------------
//
USTRUCT()
struct FManusReplicatedData
{
	GENERATED_BODY()

	UPROPERTY()
	TArray<FManusReplicatedFrameData> ReplicatedFrameDataArray;
};

/// @brief AManusReplicator class is used to replicate the Manus data sent through Live Link
/// for each Manus Live Link User (one Manus Live Link User being associated with one Live Link subject).
UCLASS(transient, notplaceable)
class AManusReplicator : public AActor
{
	GENERATED_BODY()

public:
	AManusReplicator();

	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

	bool IsLiveLinkSourceLocal();

	void OnLiveLinkTicked();
	
	UFUNCTION(Server, Unreliable, WithValidation)
	void SendReplicatedDataToServer(FManusReplicatedData DataToReplicate); //this is generated by unreal , so ignore the local not defined function warning.

	UFUNCTION()
	void OnReplicatedDataReceivedFromServer();

	static void CompressReplicatedFrameData(const FLiveLinkAnimationFrameData& UncompressedFrameData, FManusReplicatedFrameData& CompressedFrameData);
	static void DecompressReplicatedFrameData(FLiveLinkAnimationFrameData& UncompressedFrameData, const FManusReplicatedFrameData& CompressedFrameData);

public:
	UPROPERTY(Transient, Replicated)
	int32 ReplicatorId;

	UPROPERTY(Transient, ReplicatedUsing = OnReplicatedDataReceivedFromServer)
	FManusReplicatedData ReplicatedData;
};

// Close the Doxygen group.
/** @} */